/**
 * Mock employee master data for the LS HR "Employee List" feature.
 *
 * NOTE: This dataset is purely for the frontend mockup. It is consumed by
 * `EmployeeList.vue` (table rows) and `EmployeeEdit.vue` (pre-filled form),
 * so both pages always stay in sync without any backend integration.
 */

export const EMPLOYMENT_STATUS_OPTIONS = ['Permanent', 'Contract'];
export const USER_STATUS_OPTIONS = ['Active', 'Deactive'];

export const EMPTY_EMPLOYEE = {
  vendor_number: '',
  user_department: '',
  department_title: '',
  vendor_name: '',
  employment_status: '',
  po_number: '',
  po_period_1: '',
  po_period_2: '',
  dic_hro: '',
  cost_center: '',
  employee_id: '',
  employee_name: '',
  position: '',
  position_group: '',
  category: '',
  site: '',
  supervisor_nik: '',
  supervisor_name: '',
  user_status: 'Active',
};

export const MOCK_EMPLOYEES = [
  {
    id: 1,
    vendor_number: 'V-001234',
    user_department: 'Mining Operation',
    department_title: 'Production',
    vendor_name: 'PT Karya Tambang Sejahtera',
    employment_status: 'Permanent',
    po_number: 'PO-2026-00112',
    po_period_1: '2026-01-01',
    po_period_2: '2026-12-31',
    dic_hro: 'Andi Pratama',
    cost_center: 'CC-3001',
    employee_id: 'NPK-100245',
    employee_name: 'Budi Santoso',
    position: 'Heavy Equipment Operator',
    position_group: 'Operator',
    category: 'Field',
    site: 'Lati',
    supervisor_nik: '880123',
    supervisor_name: 'Rian Hidayat',
    user_status: 'Active',
  },
  {
    id: 2,
    vendor_number: 'V-001234',
    user_department: 'Mining Operation',
    department_title: 'Production',
    vendor_name: 'PT Karya Tambang Sejahtera',
    employment_status: 'Contract',
    po_number: 'PO-2026-00112',
    po_period_1: '2026-01-01',
    po_period_2: '2026-12-31',
    dic_hro: 'Andi Pratama',
    cost_center: 'CC-3001',
    employee_id: 'NPK-100312',
    employee_name: 'Siti Aminah',
    position: 'Mining Foreman',
    position_group: 'Supervisor',
    category: 'Field',
    site: 'Lati',
    supervisor_nik: '880123',
    supervisor_name: 'Rian Hidayat',
    user_status: 'Active',
  },
  {
    id: 3,
    vendor_number: 'V-002981',
    user_department: 'Plant Maintenance',
    department_title: 'Maintenance',
    vendor_name: 'PT Mitra Alat Berat',
    employment_status: 'Permanent',
    po_number: 'PO-2026-00208',
    po_period_1: '2026-02-01',
    po_period_2: '2027-01-31',
    dic_hro: 'Lina Marlina',
    cost_center: 'CC-4012',
    employee_id: 'NPK-200118',
    employee_name: 'Hendra Wijaya',
    position: 'Mechanic Senior',
    position_group: 'Senior Staff',
    category: 'Workshop',
    site: 'Sambarata',
    supervisor_nik: '870456',
    supervisor_name: 'Yusuf Maulana',
    user_status: 'Active',
  },
  {
    id: 4,
    vendor_number: 'V-002981',
    user_department: 'Plant Maintenance',
    department_title: 'Maintenance',
    vendor_name: 'PT Mitra Alat Berat',
    employment_status: 'Contract',
    po_number: 'PO-2026-00208',
    po_period_1: '2026-02-01',
    po_period_2: '2027-01-31',
    dic_hro: 'Lina Marlina',
    cost_center: 'CC-4012',
    employee_id: 'NPK-200145',
    employee_name: 'Joko Susilo',
    position: 'Welder',
    position_group: 'Operator',
    category: 'Workshop',
    site: 'Sambarata',
    supervisor_nik: '870456',
    supervisor_name: 'Yusuf Maulana',
    user_status: 'Deactive',
  },
  {
    id: 5,
    vendor_number: 'V-003457',
    user_department: 'HSE',
    department_title: 'Safety & Environment',
    vendor_name: 'PT Sinergi Karya Utama',
    employment_status: 'Permanent',
    po_number: 'PO-2026-00377',
    po_period_1: '2026-03-15',
    po_period_2: '2027-03-14',
    dic_hro: 'Dewi Lestari',
    cost_center: 'CC-5005',
    employee_id: 'NPK-300089',
    employee_name: 'Rahmat Hidayat',
    position: 'HSE Officer',
    position_group: 'Staff',
    category: 'Office',
    site: 'Binungan',
    supervisor_nik: '890234',
    supervisor_name: 'Anita Kusuma',
    user_status: 'Active',
  },
  {
    id: 6,
    vendor_number: 'V-003457',
    user_department: 'HSE',
    department_title: 'Safety & Environment',
    vendor_name: 'PT Sinergi Karya Utama',
    employment_status: 'Permanent',
    po_number: 'PO-2026-00377',
    po_period_1: '2026-03-15',
    po_period_2: '2027-03-14',
    dic_hro: 'Dewi Lestari',
    cost_center: 'CC-5005',
    employee_id: 'NPK-300102',
    employee_name: 'Nurul Aisyah',
    position: 'Safety Inspector',
    position_group: 'Staff',
    category: 'Office',
    site: 'Binungan',
    supervisor_nik: '890234',
    supervisor_name: 'Anita Kusuma',
    user_status: 'Active',
  },
  {
    id: 7,
    vendor_number: 'V-004102',
    user_department: 'Logistics',
    department_title: 'Supply Chain',
    vendor_name: 'PT Cipta Logistik Mandiri',
    employment_status: 'Contract',
    po_number: 'PO-2026-00455',
    po_period_1: '2026-04-01',
    po_period_2: '2026-09-30',
    dic_hro: 'Fajar Nugroho',
    cost_center: 'CC-6020',
    employee_id: 'NPK-400063',
    employee_name: 'Agus Setiawan',
    position: 'Logistics Coordinator',
    position_group: 'Staff',
    category: 'Office',
    site: 'Lati',
    supervisor_nik: '860789',
    supervisor_name: 'Bambang Suryanto',
    user_status: 'Deactive',
  },
];

export const findEmployeeById = (id) => {
  const numId = Number(id);
  if (!Number.isFinite(numId)) return null;
  return MOCK_EMPLOYEES.find((e) => e.id === numId) || null;
};
