ALTER TABLE employees 
ADD COLUMN nama_karyawan VARCHAR(150) NOT NULL AFTER id,
ADD COLUMN jabatan VARCHAR(100) DEFAULT NULL,
ADD COLUMN department VARCHAR(100) DEFAULT NULL,
ADD COLUMN vendor_id INT DEFAULT NULL,
ADD COLUMN site VARCHAR(100) DEFAULT NULL,
ADD COLUMN nik_atasan VARCHAR(50) DEFAULT NULL,
ADD COLUMN nama_atasan VARCHAR(150) DEFAULT NULL;

ALTER TABLE employees
ADD CONSTRAINT fk_employees_vendor
FOREIGN KEY (vendor_id) REFERENCES vendors(id)
ON UPDATE CASCADE
ON DELETE SET NULL;